spring:
  application:
    name: cloud-eureka-server

---
server:
  port: 8300

eureka:
  instance:
    hostname: eurekaserver1
  client:
    service-url:
      defaultZone: http://eurekaserver2:8301/eureka/
spring:
  profiles: eurekaserver1
---
server:
  port: 8301

eureka:
  instance:
    hostname: eurekaserver2
  client:
    service-url:
      defaultZone: http://eurekaserver1:8301/eureka/
spring:
  profiles: eurekaserver2