spring:
  application:
    name: cloud-eureka-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver1:8300/eureka/,http://eurekaserver2:8301/eureka/,http://eurekaserver3:8302/eureka/
---
spring:
  profiles: eurekaserver1
eureka:
  instance:
    hostname: eurekaserver1
server:
  port: 8300
---
spring:
  profiles: eurekaserver2
eureka:
  instance:
    hostname: eurekaserver2
server:
  port: 8301
---
spring:
  profiles: eurekaserver3
eureka:
  instance:
    hostname: eurekaserver3
server:
  port: 8302